sudo: false
language: scala
scala:
  - "2.11.7"
script:
  - sbt clean coverage intervalsetJVM/test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sbt coveralls
branches:
  only:
    - master
cache:
  directories:
    $HOME/.ivy2/cache
